name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: make install-deps
      - name: Hardhat tests
        run: |
          make start-hardhat 1>/dev/null 2>/dev/null &
          make test-hardhat

  test-ovm:
    name: Test OVM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout optimism
        run: git clone https://github.com/ethereum-optimism/optimism.git
      - name: Install optimism
        run: |
          cd optimism/ops
          docker-compose build
          docker-compose up -d
          date
      - name: Run OVM tests 
        run: |
          npm install wait-on
          date
          npx wait-on http://localhost:8545 -t 500000 || true
          date
          make test-ovm

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM install
        run: npm install
      - name: Run coverage
        run: ./node_modules/.bin/truffle run coverage -solcoverjs ./scripts/.solcover.js --network test
      - name: Coverall
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}